version: "2.2"
services:
  api:
    image: contest-winning
    command: python /app/api.py
    links:
      - mysql:db
    ports:
      - 5000:5000
    volumes:
      - .:/app
    working_dir: /app

  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'contest-winning'
    ports:
      - 3333:3306
